{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "budgetwise.fullname" . }}-mongodb
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "budgetwise.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "budgetwise.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}