apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "budgetwise.fullname" . }}-perfin
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "budgetwise.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "budgetwise.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "budgetwise.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "budgetwise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: perfin
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.perfin.image.repository }}:{{ .Values.perfin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.perfin.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.perfin.service.port }}
              protocol: TCP
        #   livenessProbe:
        #     httpGet:
        #         path: /
        #         port: http
        #     initialDelaySeconds: 30
        #     periodSeconds: 10
        #     timeoutSeconds: 5
        #     failureThreshold: 6
        #   readinessProbe:
        #     httpGet:
        #         path: /
        #         port: http
        #     initialDelaySeconds: 5
        #     periodSeconds: 5
        #     timeoutSeconds: 3
        #     failureThreshold: 3
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.perfin.env.SPRING_DATASOURCE_URL | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "budgetwise.postgresql-secret-name" . }}
                  key: postgresql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "budgetwise.postgresql-secret-name" . }}
                  key: postgresql-password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}