apiVersion: v1
kind: Service
metadata:
  name: {{ include "budgetwise.fullname" . }}-perfin
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "budgetwise.labels" . | nindent 4 }}
    app: perfin
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.perfin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "budgetwise.selectorLabels" . | nindent 4 }}
    app: perfin