---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: budgetwise
spec:
  encryptedData:
    postgresql-password: AgCBzrOPHjO1Yu73iSsIESgpufiVmthV9uDnUHQbW/N8Mbpp9ORsz4PPsZTm3uSrSSs2GUwOC8Mz1nHRNZLeTSJdi20yNzgFdbcsTndnShz+wiRz+NgIiCoB/T380M/1x9mxQQni0iEPxjpi2bUdKvwJ8UDzdmXkzWgGSrRcJ1aKMc8N9IAhDp5oG54KGrp8EckNwPoDClvhYLVQIVrjMf8L6zAKFUVTpznxwiM3KM6zQqLPIypQ5uRy6Y0bz/dLqfwOwfOUdcMF7s5RdsdRRXc0DyWJITQFg5lBtiZYHpdRUDp+zu6eGgp9ahatqjp19S5QjJpGTMrQRJ0wB1de14oebmnIweCsB0+rpU73vlT88KQa7pFjSFoMVLyvFsFt9UZUAkR0i1I61R6qv8pruVRl6MLtzxuYbEM0xm2BccCKudoRZIBlltwDEhNxxu6oIZQcjwb50EK+wJ9+x0E0fhVVhmP/WgT0arUXGjWYcj2YbzmXOp0Egbzy1YTYs8ci2wqEZ4Dd3BBR764QYlWIUdvqXCjfuwyXDmwKMURzMQQnTaX7sTQrGOQ09sBmOKPhB3v1y6q4dB8aAhPg9WrjWMrMbQEoMKp0/3xv6Flau4BYAbLw2XV0CvxqU0T6uYRznCqKxopKET+e0/cLkhJPcKFs0p1Fspv9ev5pRzV3L2P5d7HVWsNZzsW49i/HWk7BlW4nGirG1wo=
    postgresql-username: AgA5z64BUnkxNZ7BvrKZmTMP9qv2K1HrbQvI37Zb0Gd1hYiwf9xs/Hw/WXaOWQfCm0dku0YjVta9UKXZyuRiNt1xstQsPRbt8925tMgFsWzXxU0gl1Qk+a5F5lQs4thhVbiOvxGMqDxODD+UYUhHKOadWemsEruavBuFRftsdvHzf/jBDc9u3nn2ufxvw0Xzgp6HBULx8QM7IgdWXBCTgZuq2W2FBtSBByrsO4Ax9BviHzK/0SDVlvzKO63Ijo6qih6dP4c8z7Ooag3s58kkrI2yp8fxOWwZO98IQKGyBBY6qpnJAu9QMW/BBhXrkrKJwUKMu416SII/jZRtCCQ0gmQLpMS63tVlSFqbkY/E0+xpNW5opa03bUQc8xQuYrg4kJZJZDJIYNHqNRYLY1zF4j7fv3f84S9mf8hzhb020bobu1myJYgBBZBl3rRWRuHYL+TKJz9EyknIHoE9rtyKrju4FySeiqYb6Zweg67KGnvPVSLUQrLszJ78yKa8+6wqDNOuTPMTo4hCgwvrGk4iUZw+w2fYmvos/DEWKP0Z1GKU0gMCk3P1HX6WH5NldAjNt9XdnQq8Zu8e2FDefyr+v36k/Ii7HL6mcgRq/naXeMq9gM+1l2hW0mrU5Iv7Wn7M9fj/rWTnrSOeCbuLMw6QXNjmLGtXGPB1cxf0XYFL2aZBSduyvW+gheMhOlKSuAENolfJ90NnqsE=
  template:
    metadata:
      name: postgresql-secret
      namespace: budgetwise
